### ISSUE TITLE
Ladder Behaviour unreliable

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/ScaffoldingBehavior#3]
Minecraft Version: 
1.15.2

Forge Version: 
1.15.2-31.1.27

Mod Version: 
railladderpower-1.15.2-1.0.0

Single Player or Server:
SP

Describe problem (what you were doing; what happened; what should have happened):
Clicking a vanilla ladder with a vanilla ladder does nothing, unless there is a ladder or air below the ladder you are clicking.

Additionally, ladders can pass through blocks a bit too effectively:
![billede](https://user-images.githubusercontent.com/21295394/77819175-0dcd6480-70d9-11ea-996a-9d65ab40a02d.png)

Log file link:
https://gist.github.com/NillerMedDild/2eb89fdd32835374a9edc53c1309dab5

**Comment by Lothrazar** [comment]
There is a config setting to disable the "building in air blocks" feature.  i left it in because it seemed fun. maybe defaulting off would be better

	#Auto Ladder Building: true means allow invalid building places such as floating in midair
		autoBuildInvalid = true

**Comment by Lothrazar** [comment]
should default to false. also config name changed it matches new jar name :)  https://www.curseforge.com/minecraft/mc-mods/scaffolding-behavior/files/2915437

**Comment by NillerMedDild** [comment]
I know about the config, the issue is that ladders can extend through blocks - so if I'm standing under ground, clicking a ladder will eventually cause ladders to pop up at the surface. As far as I understand, ladders should only be placed on top of or below another ladder, right?

**Comment by Lothrazar** [comment]
Oh that behavior, how its skipping over stones sticking out i can look at that

**Comment by NielsPilgaard** [comment]
This was fixed back then, forgot to close :) ty!
